### ISSUE TITLE
markdown list exclude from actual usage, table of contents

### ISSUE THREAD

**Issue by abkrim** [saleem-hadad/larecipe#288]
Currently, the recipe treats the first list created with markdown in the document as a table of contents item.

However, there are many situations in which one does not want to incorporate that list into the table of contents, or at least, wants the list to also appear in the text in addition to being parsed as a table of contents

**Comment by corazzi** [comment]
In my case, I don't want to make use of this feature at all.

I have created a custom theme, and as part of the customisations I've included these overrides:

```css
.documentation>ul:first-of-type {
    position: initial;
    width: initial;
    top: initial;
    right: initial;
    list-style: initial;
    padding: revert;
}

.documentation>ul:first-of-type li {
    border: unset;
    line-height: initial;
    padding: 0.25rem;
}

.documentation>ul:first-of-type li a {
    color: inherit;
    font-size: inherit;
}

.documentation>ul li,
.documentation>ol li {
    padding: 0.25rem;
}

.documentation li a {
    color: inherit;
}
```

So now this page:

```markdown
# List example page

* The
* First
* List
* [And a link](#)

---

* The
* Second
* List
* [And a link](#)
```

looks like this:

![larecipe list](https://github.com/saleem-hadad/larecipe/assets/915909/24e0a39b-d19c-4257-9c9c-ce507e0b47d8)

If, like me, you don't want to use this at all, you may also want to add something like this to your theme for a full width documentation area:

```css
.documentation {
    width: 100%;
    padding-right: 4rem;
}
```

Hope this helps someone!
